= Adding Spring Cloud Config to Boot Application

In this lab we'll utilize Spring Boot and Spring Cloud to configure our application from a configuration dynamically retrieved from a git repository. We'll then deploy it to Pivotal Cloud Foundry and auto-provision an instance of a configuration server using Pivotal Spring Cloud Services.

== Update _Hello_ REST service

. These features are added by adding _spring-cloud-starter-config_ to the classpath.  During our initial project setup with *start.spring.io* we've already included that.

. Verify the Spring Cloud Config dependency the following file: */cloud-native-spring/pom.xml*.  You should see the following dependency in the list:
+
[source, xml]
---------------------------------------------------------------------
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-starter-config</artifactId>
</dependency>
---------------------------------------------------------------------

. Add an @Value annotation, private field, and associated usage to the class _io.pivotal.CloudNativeSpringApplication_ (/cloud-native-spring/src/main/java/io/pivotal/CloudNativeApplication.java):
+
[source, java, numbered]
---------------------------------------------------------------------
    @Value("${greeting:Hello}")
    private String _greeting;

    @RequestMapping("/")
    public String hello() {
        return _greeting + " World!";
    }
---------------------------------------------------------------------
+
Completed:
+
[source,java,numbered]
---------------------------------------------------------------------
package io.pivotal;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.data.rest.RepositoryRestMvcAutoConfiguration;
import org.springframework.context.annotation.Import;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@RestController
@EnableJpaRepositories
@Import(RepositoryRestMvcAutoConfiguration.class)
public class CloudNativeSpringApplication {

	public static void main(String[] args) {
		SpringApplication.run(CloudNativeSpringApplication.class, args);
	}

	@Value("${greeting:Hello}")
	private String _greeting;

	@RequestMapping("/")
	public String hello() {
		return _greeting + " World!";
	}
}
---------------------------------------------------------------------

== Run the _cloud-native-spring_ Application and verify dynamic config is working

. Run the application
+
$ mvn clean spring-boot:run

. Browse to http://localhost:8080 and verify you now see your new greeting.

. Stop the _cloud-native-spring_ application

== Create Spring Cloud Config Server instance

.

. Now we must create a temporary default value for the property.  Add the following to */cloud-native-spring/src/main/resources/application.yml*:
+
[source, yaml]
---------------------------------------------------------------------
greeting: Hola
---------------------------------------------------------------------

== Deploy and test application




